language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
- nightly
- pypy
script:
- bandit -r .
- flake8 .
notifications:
  irc: irc.0x00sec.org#legobot
  on_success: change
  on_failure: always
  use_notice: true
deploy:
  provider: pypi
  user: briggsb
  on:
    tags: true
  password:
    secure: NaatR1/AXchvJOffqoSmazug4oB6zg9APEJgP9RPQpjhcDS/AUwWgsp7hkH3WVRxQOVyF33BPVxvEAmUiqUMQFKmf2r/q6BovuRy67xJSM4dkXvNYaJTMD+LQKIGzAgxVKsVprTPJc1fxSnET+dYtW/cY9DocAttPSZKk0iZffoSWfvYFjWXZ7z0hT6iltQVDl2OlqlH4dHSoeMzLLqQEiJ0AhDD2A4AF8wTzfjBL9YPJyMPAd6qKgGMpyNxZG/zJ4sgp0sJa5Xfch57Z0HlMosjXnhw0a15pmzoYaZnTkfqZwZ11FMJgLxwUBGEbTFGUbT9jy5yK+YoHmHH/865KHacTs1791yofLjDWWawuu1SN9Qgz1h0MA/DoQB54ZAJsDl5P0ot4g7uuMxyfmqqINmKh2Uj4nMQoiLPNqDgOspm1ByTSygr0FIWMpieyELon/wWK/v6608r8rsOUZIUI2wA7PXc6bVFc68gpjA01JE21W+r6LgNZDQB7rHgV0SxHNSX2RFldiMTRCPnKqCsdKJ1d8mIzzgiQb9YKfwoBa1kPrlbN+z0oRp57JjHJ+/OmlUjL8ZGvhh3R5V734CK7NjgprnKBP7qzFa3bfz5hhXGsnme9GcDc9tkWmoWrItGnQRdVlVP6jYBy1fe+T7Gs0y+C76al+mSCShbpz6AoGA=
distributions: sdist bdist_wheel
